nodeLinker: node-modules

npmScopes:
  jaclight:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    
yarnPath: .yarn/releases/yarn-4.0.2.cjs
