export enum ComponentName {
  CollectionBuilder = 'CollectionBuilder',
  Widget = 'Widget',
  Post = 'Post',
  Comment = 'Comment',
  Navigation = 'Navigation',
  Category = 'Category',
  Social = 'Social',
  Settings = 'Settings',
  UserGroup = 'UserGroup',
  PasswordPolicy = 'PasswordPolicy',
  Authentication = 'Authentication',
  Monitoring = 'Monitoring',
  Logs = 'Logs',
  Trash = 'Trash',
  Mintflow = 'Mintflow',
  Publish = 'Publish',
  Draft = 'Draft',
  Workflow = 'Workflow',
  Function = 'Function',
  RolePermission = 'RolePermission',
  MessageTemplate = 'MessageTemplate',
  Language = 'Language',
  ActivityFeed = 'ActivityFeed',
  Application = 'Application',
}
