export enum ConfigType {
    Email = "Email",
    Integration = "Integration",
    Database = "Database",
    Device = "Device",
    Server = "Server",
    MQTT = "MQTT",
    AWS = "AWS",
    GOOGLE="GOOGLE",
    MICROSOFT="MICROSOFT",
    PostgresSQL = "PostgresSQL",
    Kafka = "Kafka",
    MySQL = "MySQL",
    MongoDB = "MongoDB",
    Payment = "Payment",
    SocialMedia = "SocialMedia",
    Analytics = "Analytics",
    Marketplace = "Marketplace",
    AI="AI"
}
