export enum ConfigType {
  Email = 'Email',
  Integration = 'Integration',
  Database = 'Database',
  Device = 'Device',
  Server = 'Server',
  MQTT = 'MQTT',
  AWS = 'AWS',
  PostgresSQL = 'PostgresSQL',
  Kafka = 'Kafka',
  MySQL = 'MySQL',
  MongoDB = 'MongoDB',
  Payment = 'Payment',
  SocialMedia = 'SocialMedia',
}
