export enum ControlType {
  paragraph = 'paragraph',
  container = 'container',
  containerLayout = 'containerLayout',
  richtext = 'richtext',
  html = 'html',
  markdown = 'markdown',
  textfield = 'textfield',
  number = 'number',
  selectSingle = 'selectSingle',
  selectMany = 'selectMany',
  date = 'date',
  file = 'file',
  code = 'code',
  uuid = 'uuid',
  color = 'Color',
  collection = 'collection',
  map = 'map',
  button = 'button',
  label = 'label',
  cron = 'cron',
  icon = 'icon',
  richSelect = 'richSelect',
  payment = 'payment',
  address = 'address',
  phone = 'phone',
  email = 'email',
  slide = 'slide',
  accordion = 'accordion',
  tab = 'tab',
  collapsible = 'collapsible',
  table = 'table',
  list = 'list',
  column = 'column',
  numberRange = 'numberRange',
  ui = 'ui',
  arrayContainer = 'arrayContainer',
  dateRange = 'dateRange',
  lookup = 'lookup',
  legalConsent = 'legalConsent',
  /**
   * An e-signature: drawn and/or typed, with explicit consent. The value sent is
   * `{ image?: data URL, typedName?, consent: true }`; the server validates it,
   * stores a drawn image as a private file and keeps a FormSignature (role,
   * signedAt, IP, user agent). Field options: `signerRole`, `signatureModes`
   * (['draw', 'type']), `inputRequired`.
   */
  signature = 'signature',
}
