export enum DataType {
  activity = 'activity',
  collection = 'collection',
  page = 'page',
  category = 'category',
  tag = 'tag',
  tag_group = 'tag_group',
  comment = 'comment',
  site = 'site',
  navigation = 'navigation',
  file = 'file',
  fileinfo = 'fileinfo',
  messagetemplate = 'messagetemplate',
  passwordpolicy = 'passwordpolicy',
  user = 'user',
  email_account_health = 'email_account_health',
  userrole = 'userrole',
  script = 'script',
  workflowdefinition = 'workflowdefinition',
  task = 'task',
  sf_price_list= 'sf_price_list',
  usergroup = 'usergroup',
  email_broadcast = 'email_broadcast',
  user_invitation = 'user_invitation',
  email_account = 'email_account',
  agent= 'agent',
  ai_assistant= 'ai_assistant',
  creative = 'creative',
  dev_environment = 'dev_environment',
  permission = 'permission',
  usage = 'usage',
  site_notice = 'site_notice',
  pipeline = 'pipeline',
  setting = 'setting',
  customer_group = 'customer_group',
  automation = 'automation',
  automation_execution = 'automation_execution',
  automation_log = 'automation_log',
  dataviz = 'dataviz',
  mintflow = 'mintflow',
  mintflownode = 'mintflownode',
  post = 'post',
  ivr_flow = 'ivr_flow',
  ivr_routing = 'ivr_routing',
  sms_routing = 'sms_routing',
  subschema = 'subschema',
  lead_pipeline = 'lead_pipeline',
  config = 'config',
  application = 'application',
  dashboard = 'dashboard',
  ticket = 'ticket',
  chat = 'chat',
  call = 'call',
  lead = 'lead',
  message = 'message',
  schedule = 'schedule',
  trash = 'trash',
  log = 'log',
  company = 'company',
  address = 'address',
  customer = 'customer',
  customer_kyc = 'customer_kyc',
  merchant_customer = 'merchant_customer', // Business accounts with invoice billing
  calllog = 'calllog',
  form = 'form',
  signed_document = 'signed_document',
  chatmessage = 'chatmessage',
  chatgroup = 'chatgroup',
  chatregister = 'chatregister',
  phone = 'phone',
  sf_attribute = 'sf_attribute',
  sf_delivery = 'sf_delivery',
  sf_giftcard = 'sf_giftcard',
  sf_invoice = 'sf_invoice',
  sf_order = 'sf_order',
  sf_product = 'sf_product',
  sf_receipt = 'sf_receipt',
  sf_refund = 'sf_refund',
  sf_shipping = 'sf_shipping',
  sf_shipping_config = 'sf_shipping_config',
  sf_rental_item = 'sf_rental_item',
  sf_rental = 'sf_rental',
  sf_rental_config = 'sf_rental_config',
  sf_subscription = 'sf_subscription',
  sf_subscription_plan = 'sf_subscription_plan',
  sf_transaction = 'sf_transaction',
  sf_wishlist = 'sf_wishlist',
  sf_brand = 'sf_brand',
  sf_collection = 'sf_collection',
  sf_cart = 'sf_cart',
  sf_return = 'sf_return',
  sf_discount = 'sf_discount',
  sf_customer_tier = 'sf_customer_tier',
  benefit = 'benefit',
  benefit_enrollment = 'benefit_enrollment',
  promotion = 'promotion',
  subscriber = 'subscriber',
  sf_marketing = 'sf_marketing',
  sf_inventory = 'sf_inventory',
  sf_inventory_intake = 'sf_inventory_intake',
  sf_inventory_transfer = 'sf_inventory_transfer',
  location = 'location',
  flexdata = 'flexdata',
  escalation = 'escalation',
  translation = 'translation',
  event = 'event',
  reservationdefinition = 'reservationdefinition',
  reservation = 'reservation',
  service_point = 'service_point',
  service_point_item = 'service_point_item',
  published = 'published',
  history = 'history',
  auraflow = 'auraflow',
  web_visit = 'web_visit',
  web_activity = 'web_activity',
  site_index = 'site_index',
  site_domain = 'site_domain',
  campaign = 'campaign',
  audience = 'audience',
  audience_criteria = 'audience_criteria',
  social_activity = 'social_activity',
  workspace = 'workspace',
  workspace_item = 'workspace_item',
  apikey = 'apikey',
  domain_registration = 'domain_registration',
  service_pricing = 'service_pricing',
  // Logistics / Delivery
  delivery_config = 'delivery_config',
  delivery_zone = 'delivery_zone',
  delivery_agent = 'delivery_agent',
  delivery_job = 'delivery_job',
  // Finance
  payout = 'payout',
  wallet = 'wallet',
  wallet_transaction = 'wallet_transaction',
  // Events
  event_ticket = 'event_ticket',
  event_session = 'event_session',
  event_participant = 'event_participant',
  event_checkin = 'event_checkin',
  // Community
  community_connection = 'community_connection',
  community_message = 'community_message',
  community_meeting = 'community_meeting',
  community_block = 'community_block',
  // Business/HR Management
  bm_employee = 'bm_employee',
  bm_timesheet = 'bm_timesheet',
  bm_payroll_run = 'bm_payroll_run',
  bm_schedule = 'bm_schedule',
  bm_pay_stub = 'bm_pay_stub',
  bm_payroll_profile = 'bm_payroll_profile',
  bm_work_order = 'bm_work_order',
  // HR - Recruitment
  bm_job_posting = 'bm_job_posting',
  bm_applicant = 'bm_applicant',
  bm_interview = 'bm_interview',
  bm_offer = 'bm_offer',
  // HR - Benefits
  bm_benefit_plan = 'bm_benefit_plan',
  bm_benefit_enrollment = 'bm_benefit_enrollment',
  // HR - Leave
  bm_leave_type = 'bm_leave_type',
  bm_leave_balance = 'bm_leave_balance',
  bm_leave_request = 'bm_leave_request',
  bm_leave_policy = 'bm_leave_policy',
  // HR - Performance
  bm_goal = 'bm_goal',
  bm_performance_review = 'bm_performance_review',
  bm_pip = 'bm_pip',
  // HR - Learning
  bm_course = 'bm_course',
  bm_certification = 'bm_certification',
  bm_learning_path = 'bm_learning_path',
  bm_course_enrollment = 'bm_course_enrollment',
  // HR - Compensation
  bm_salary_grade = 'bm_salary_grade',
  bm_compensation_change = 'bm_compensation_change',
  bm_bonus = 'bm_bonus',
  // HR - Organization
  bm_department = 'bm_department',
  bm_position = 'bm_position',
  bm_org_chart = 'bm_org_chart',
  // HR - Documents & Compliance
  bm_employee_document = 'bm_employee_document',
  bm_policy = 'bm_policy',
  bm_policy_acknowledgement = 'bm_policy_acknowledgement',
  // HR - Offboarding
  bm_offboarding = 'bm_offboarding',
  bm_exit_interview = 'bm_exit_interview',
  // Restaurant/Hospitality
  bm_floor_plan = 'bm_floor_plan',
  bm_table = 'bm_table',
  bm_section = 'bm_section',
  bm_fulfillment = 'bm_fulfillment',
  bm_tab = 'bm_tab',
  // Client Apps
  client_app = 'client_app',
  // Banking
  bank_account = 'bank_account',
  bank_account_holder = 'bank_account_holder',
  bank_transfer = 'bank_transfer',
  bank_card = 'bank_card',
  ledger_account = 'ledger_account',
  ledger_entry = 'ledger_entry',
  journal_entry = 'journal_entry',
  // Merchant Services / Payment Links
  sf_payment_link = 'sf_payment_link',
  sf_checkout_session = 'sf_checkout_session',
  sf_payment_button = 'sf_payment_button',
  // Loans
  loan = 'loan',
  loan_application = 'loan_application',
  loan_payment = 'loan_payment',
  // Money Market / High-Yield Savings
  money_market_account = 'money_market_account',
  interest_rate_tier = 'interest_rate_tier',
  // Investments / Treasury
  investment_account = 'investment_account',
  treasury_holding = 'treasury_holding',
  certificate_of_deposit = 'certificate_of_deposit',
  investment_transaction = 'investment_transaction',
  // Security
  user_device = 'user_device',
  user_security = 'user_security',
  two_factor_backup = 'two_factor_backup',
}
