export enum DataType {
  collection = 'collection',
  page = 'page',
  category = 'category',
  tag = 'tag',
  comment = 'comment',
  site = 'site',
  navigation = 'navigation',
  file = 'file',
  messagetemplate = 'messagetemplate',
  passwordpolicy = 'passwordpolicy',
  user = 'user',
  userrole = 'userrole',
  script = 'script',
  workflowdefinition = 'workflowdefinition',
  usergroup = 'usergroup',
  permission = 'permission',
  setting = 'setting',
  collectionview = 'collectionview',
  collectionform = 'collectionform',
  mintflow = 'mintflow',
  mintflownode = 'mintflownode',
  post = 'post',
  postschema = 'postschema',
  config = 'config',
  application = 'application',
  ticket = 'ticket',
}
