export enum FieldType {
  paragraph = 'Paragraph',
  container = 'Container',
  richtext = 'Rich Text Editor',
  textfield = 'Text Field',
  numberfield = 'Number Field',
  selectionsingle = 'Single Selection',
  selectionmultiple = 'Multiple Selection',
  date = 'Date',
  file = 'File',
  code = 'Code',
  uuid = 'UUID',
  color = 'Color',
  dataField = 'Data Field',
  static = 'Static',
  collection = 'Collection',
  map = 'Map',
  derivedField = 'Derived Field',
  lookupField = 'Lookup Field',
  linkedSelect = 'Linked Selection',
  button = 'button',
}
