export enum FieldType {
    paragraph = 'Paragraph',
    container = 'Container',
    richtext = 'Rich Text Editor',
    textfield = 'Text Field',
    numberfield = 'Number Field',
    selectionsingle = 'Single Selection',
    selectionmultiple = 'Multiple Selection',
    date = 'Date',
    upload = 'Upload',
    code = 'Code',
    uuid = 'UUID',
    color = 'Color',
    ComputedField = 'Computed Field',
    dataField = 'Data Field',
    static = 'Static',
}