export const siteCategories = [
    'Home Inspection',
    'Tree Service',
    'Event Planning',
    'Drywall',
    'Carpentry',
    'Private Investigating',
    'Esthetician',
    'Chiropractor',
    'Chimney Sweep',
    'Garage Door Services',
    'Computer Repair',
    'Artificial Intelligence',
    'Interior Design',
    'Dentist',
    'General Contracting',
    'Pressure Washing',
    'Software',
    'Life Coaching',
    'Shop',
    'Glass Repair and Installation',
    'Demolition Contractor',
    'Content Writing',
    'Consulting',
    'Window Cleaning',
    'Concrete',
    'Towing',
    'Tutoring',
    'Insurance Broker',
    'Beauty',
    'Chef',
    'Blogger',
    'Boat Detailing',
    'Digital Development and Design',
    'Design',
    'Video Production',
    'Hair Salon',
    'Excavation',
    'Recruiting',
    'Security',
    'Handyman',
    'Electrician',
    'Dog Training',
    'Personal Training',
    'Contractor',
    'Tour Guide',
    'Cafe',
    'Online Learning',
    'Paving',
    'Car Detailing',
    'Project Management',
    'Acupuncture',
    'Physiotherapy',
    'IT Consulting',
    'Electrical Contracting',
    'Midwife',
    'Garage Door',
    'Financial Management and Consulting',
    'Property Management',
    'Dog Walking',
    'Public Relations',
    'Soft Washing',
    'Personal Organization',
    'Jewelry',
    'Bookkeeping',
    'Education',
    'Architecture',
    'Makeup Artist',
    'Pet Sitting',
    'DJ',
    'Marketing Agency',
    'School',
    'Content Creator',
    'UI/UX Design',
    'Law Firm',
    'Landscaping',
    'House cleaning',
    'Locksmith',
    'Fence Services',
    'Audio Production',
    'Music Instruction',
    'Food Delivery',
    'Business Consulting',
    'Locksmith Services',
    'Gaming',
    'Career Coaching',
    'Pool & Spa Services',
    'Editing',
    'Massage Therapy',
    'Roofing',
    'Affiliate Marketing',
    'Social Media Agency',
    'Online Store',
    'Accommodation',
    'Digital Marketing',
    'Photography',
    'Cleaning',
    'Bike Mechanic',
    'Gardening',
    'Yoga Instruction',
    'Taxi',
    'Art Restoration',
    'Women\'s Fashion',
    'Restoration',
    'Video Gaming',
    'Snow Removal',
    'Virtual Assistant',
    'News',
    'Construction',
    'Fitness',
    'Coaching',
    'Installation Services',
    'Property Maintenance',
    'Accounting',
    'Auto Detailing',
    'Graphic Design',
    'Travel Agency',
    'Social Media Marketing',
    'Mechanical Contracting',
    'Restaurant',
    'Men\'s Fashion',
    'Real estate',
    'Real Estate Development',
    'Pizza Restaurant',
    'Catering',
    'Elevator Services',
    'Food',
    'Copywriting',
    'Furniture Restoration',
    'Retail Store',
    'Landscape Design',
    'Video Editing',
    'Psychic',
    'Real Estate Investment',
    'Plumber',
    'Carpet Cleaning',
    'Mechanic',
    'Audio Editing',
    'Coffee Shop',
    'Barber Shop',
    'Financial Planning',
    'Remodeling',
    'Mortgage Broker',
    'Well Water Services',
    'Janitorial Services',
    'Church',
    'Resume Writing',
    'Sports Instruction',
    'Solar Repair and Installation',
    'Influencer Marketing',
    'Illustrating',
    'Mobile Repair',
    'Bar',
    'Software Development',
    'Marketing',
    'Tree Care',
    'Tourism',
    'Counselling',
    'Bakery',
    'Online Entertainment',
    'Grant Writing',
    'Nail Salon',
    'Non - profit',
    'Translation',
    'Junk Removal',
    'Technology',
    'Flooring',
    'Power Washing',
    'Real Estate Agent',
    'Information Technology',
    'Appliance Repair',
    'Lactation Consulting',
    'HVAC',
    'Irrigation Services',
    'Real Estate and Construction Consulting',
    'Hair Stylist',
    'Web Design',
    'Piano Repair',
    'Tiling',
    'Trucking',
    'Art',
    'Pest Control',
    'Pool Cleaning',
    'Fashion',
    'Web Development',
    'Production and Construction Management',
    'House Painting',
    'Writing',
    'Doctor',
    'Window Washing',
    'Videography',
    'Psychology',
    'Social Media Management',
    'Arborist',
    'Hotel',
    'Plumbing',
    'Marketing Consulting',
    'Clothing',
    'Wellness Consultant',
    'Lawn Care',
    'Music',
]
export const designEmotions = ['happy', 'warm', 'welcoming', 'neutral', 'Professional', 'trustworthy', 'Exciting', 'energetic', 'Calm', 'peaceful']
export const designStyles = ['modern', 'classic', 'retro', 'vintage', 'futuristic', 'minimalist', 'grunge', 'art/deco', 'bohemian', 'shabby/chic', 'industrial', 'mid-century', 'scandinavian', 'contemporary']
export const siteSectionsTypes = [
    "Home",
    "Header",
    "Header with Logo",
    "Header with Navigation and Logo",
    "Navigation",
    "Hero Section",
    "About Us",
    "Services Overview",
    "Product Showcase",
    "Testimonials",
    "Portfolio Display",
    "Case Studies",
    "Blog Section",
    "News Updates",
    "Contact Form",
    "Contact Form with Map",
    "Call to Action (CTA)",
    "FAQs",
    "Footer",
    "Footer with Navigation",
    "Footer with Logo",
    "Footer with Logo and Navigation",
    "Footer with Contact Information",
    "Subscription Form",
    "Team Members",
    "Gallery",
    "Event Calendar",
    "Newsletter Signup",
    "Social Proof",
    "Client Logos",
    "Media Mentions",
    "Features Highlight",
    "Benefits Explanation",
    "Pricing Table",
    "Legal Information",
    "Press/Media Coverage",
    "Map",
    "Review Summary",
    "Promotional Banner",
    "Feature Comparison Chart",
    "Video Introduction",
    "Interactive Elements",
    "Product/Service Features",
    "Contact Information",
    "Search Bar",
    "Login/Register",
    "Resource Downloads",
    "Customer Support",
    "Awards and Certifications",
    "User Testimonials",
    "Product Demos",
    "Blog Categories",
    "Case Study Summaries",
    "Related Articles",
    "Project Thumbnails",
    "Service Descriptions",
    "Product Descriptions",
    "Photo Slider",
    "Lead Capture Form",
    "Limited Time Offers"
]

//Site Category and Recommended Sections/required sections -- ai can pick others
//use can request to add or remove sections

// const pageJson = {
//     "name": "Upwind Site",
//     "template": "Upwind site template",
//     "description": "A modern and clean site template",
//     "type": "page",
//     "categories": ["business", "modern"],
//     "tags": ["responsive", "clean"],
//     classification: {
//     },
//     sections: ['section-1'],
//     layout: '<div class="upwind-site">...</div>',
// }

// const sectionJson = {
//     "id": "section-1",
//     "template": "Upwind site template",
//     "description": "A modern and clean site template",
//     "type": "section",
//     classification: {

//     },
//     "categories": ["business", "modern"],
//     "tags": ["responsive", "clean"],
//     "html": "<div class='upwind-site'>...</div>",
// }