name: publish Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} 
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      # Uncomment the following line if you have tests
      # - name: Run tests
      #   run: yarn test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
          always-auth: true

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure Git
        run: |
          git config --global user.email "imolewolede@gmail.com"
          git config --global user.name "$GITHUB_ACTOR"

      - name: Bump version and push tags
        run: |
          yarn version minor
          git push --follow-tags
          git push

      - name: Publish to GitHub Package Registry
        run: npx npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
